### ISSUE TITLE
Bug multi-extensions

### ISSUE THREAD

**Issue by Aza1337** [maurosoria/dirs3arch#6]
Hi,
thanks for the tool, i've detected that it does not handle multi-extensions mode correctly.
Here is the correction to apply : 

In lib/core/FuzzerDictionnary.py : 
Replace 

            if '%EXT%' in line:
                for extension in self._extensions:
                    entry = (line.replace('%EXT%', extension))
            self.entries.append(urllib.quote(entry))

by : 

            if '%EXT%' in line:
                for extension in self._extensions:
                    entry = (line.replace('%EXT%', extension))
                    self.entries.append(urllib.quote(entry))

(indentation problem ;) )

regards

**Comment by maurosoria** [comment]
Hi Aza1337,

Yes, you're aboslotely righ. I apparently introduced this bug in this commit (https://github.com/maurosoria/dirs3arch/commit/1d62282d26525459e3092912f3c575b80f3aaf1b#diff-380daa7d4a9ca7829abb5995249f4791)

I'll be releasing a fix for this issue soon.

Thanks :)
