### ISSUE TITLE
failed to join url path during scanning.

### ISSUE THREAD

**Issue by all3g** [maurosoria/dirs3arch#8]
When dirs3arch is used to scan php file, a bug appears.  What i'v done,

```
[all3g@core dirs3arch]$ python3 dirs3arch.py -u http://192.168.1.101/ -e "php" -w ~/sectools/fuzzdb/discovery/wordlists.txt -t 20
```

This is my wordlist file:

    123
    phpinfo
    core
    main
    ...

dirs3arch fails to get the right url path, and the error url is **/123?** during scanning.
What we need is **/123.php**.  

**HTTP Response as follow:** 

```
GET /123? HTTP/1.1
Connection: keep-alive
Accept-Encoding: identity
User-agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1468.0 Safari/537.36
Host: 192.168.1.101
Cache-Control: max-age=0
Accept-Language: en-us
Keep-Alive: 300

HTTP/1.1 404 Not Found
Date: Sun, 22 Mar 2015 10:05:49 GMT
Server: Apache/2.4.10 (Win32) OpenSSL/1.0.1h PHP/5.4.31
Vary: accept-language,accept-charset
Accept-Ranges: bytes
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8
Content-Language: en
```

**Comment by maurosoria** [comment]
Actually there is no bug, this is by design.

You should append ".%EXT%". For example:

admin/
index.%EXT%

With "-e asp,aspx" should generate this dictionary:

admin/
index.asp
index.aspx
